name: "${name}"
version: "${project_version}"
author: "${author}"
api-version: "${minecraft_version}"
main: com.dragon.lastlife.Initializer
bootstrapper: com.dragon.lastlife.Bootstrapper
loader: com.dragon.lastlife.Loader
